[core]
interface = "br-6528083c3c1a"
workdir = "./runs"
db_path = "./state.sqlite"
reset_previous_runs = true
reset_database = true
target_cidr = ""

[report]
output_dir = "./reports"

[logging]
level = "DEBUG"

[discovery]
method = "nmap"
nmap_args = "-sn"
nmap_timing = "T5"
nmap_min_rate = 0
nmap_max_rate = 0
large_hosts_threshold = 4096
arp_fallback_timeout_seconds = 300
resolve_hostnames = true
resolver_timeout_ms = 300
resolver_threads = 32
enable_avahi = true

[port_scan]
nmap_timing = "T4"
tcp_top_ports = 1000
tcp_min_rate = 50
tcp_max_rate = 150
host_timeout_seconds = 180
batch_size = 16
max_retries = 1
overall_timeout_seconds = 900
use_pn = true
udp_ports = [53,67,69,123,137,138,161,162,500,514,520,631,1434,1701,1900,4500,5353]

[os_obsolescence]
nmap_timing = "T5"
host_timeout_seconds = 45
batch_size = 16
max_retries = 1
overall_timeout_seconds = 240
oscan_guess = true
oscan_limit = false
use_pn = true
rules_path = "data/nmap_os_comments.jsonl"
enable_rules_fallback = true
strict_unambiguous_only = true

[service_fingerprint]
nmap_timing = "T4"
host_timeout_seconds = 180
max_retries = 1
min_rate = 50
max_rate = 150
version_intensity = 2
enable_vulners = true
vulners_mincvss = 7
scripts = ""

[auth_bruteforce]
host_timeout_seconds = 20
per_target_max_attempts = 6
delay_ms = 200
enable_ssh = true
enable_ftp = true
enable_telnet = true
enable_snmp = true
